[package]
authors = ["you"]
description = "A Tauri App"
edition = "2021"
license = ""
name = "send-file-core"
repository = ""
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.2", features = [] }

[dependencies]
axum = {version = "0.6.12", features = ["multipart"] }
dirs = "5.0.0"
filesize = "0.2.0"
glob = "0.3.1"
local-ip-address = "0.5.1"
portpicker = "0.1.1"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = {version = "1.2", features = ["dialog-all", "fs-all", "path-all", "shell-open"] }
tauri-plugin-store = {git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev"}
tauri-plugin-upload = {git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev"}
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
tokio = {version = "1.26.0", features = ["full"] }
tower-http = {version = "0.4.0", features = ["cors", "limit", "trace"] }
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", features = ["env-filter"] }
axum_typed_multipart = "0.3.2"
reqwest = "0.11.16"
lazy_static = "1.4.0"
walkdir = "2.3.3"
sys-info = "0.9.1"
uptime_lib = "0.2.2"
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
